import './globals.css';
import { Inter } from 'next/font/google';
import { ReduxProvider } from './redux_files/provider';


const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'React Redux',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* suppressHydrationWarning={true} used here to remove some console error */}
      <body className={inter.className} suppressHydrationWarning={true}>
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  )
}
